[package]
name = "ape-bytebeats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ape-core = { path = "../ape-core" }
rlua = "0.19.4"
